name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Setup uv
        uses: astral-sh/setup-uv@v1
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Bytecode build check
        run: uv run python -m compileall src

  mypy:
    name: mypy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Setup uv
        uses: astral-sh/setup-uv@v1
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run mypy
        run: uv run mypy src
